[package]
name = "ecosystem-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
rand_distr = "0.4.3"
rand = "0.8.5"
lazy_static = "1.4.0"
ordered-float = "4.2.0"
plotters = "0.3.5"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "benchmark"
path = "src/benchmark.rs"
